[manifest]
version = "1.0.0"
dump_lua = true
priority = 99999

[[patches]]
[patches.regex]
target = "game.lua"
pattern = '''SMODS\.quip\(\"loss\"\)'''
position = "at"
payload = '''SMODS.quip(G.GAME.incompatible_stake_error and "bld_incompat" or (BLINDSIDE.hasBlindside() and "bld_loss" or "loss"))'''
match_indent = true

[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''SMODS\.quip\(\"win\"\)'''
position = "at"
payload = '''SMODS.quip(BLINDSIDE.hasBlindside() and "bld_win" or "win")'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''Jimbo = Card_Character(extra)'''
position = "after"
payload = '''
if extra.googly and Jimbo.children.card then
    Jimbo.googly = true
    Jimbo.children.card.googly = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''Jimbo = Card_Character(extra)'''
position = "after"
payload = '''
if extra.googly and Jimbo.children.card then
    Jimbo.googly = true
    Jimbo.children.card.googly = true
end
'''
match_indent = true


